{{- if .Values.containerService }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "xnat.csReadyName" . }}
  labels:
    {{- include "xnat.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "xnat.serviceAccountName" . }}
  namespace: {{ include "xnat.namespace" . | quote }}
roleRef:
  kind: ClusterRole
  name: {{ include "xnat.csReadyName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}