{{ if not .Values.cnpg.cluster.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xnat.postgresql.fullname" . }}
  labels:
{{- include "xnat.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.cnpg.external.postgresqlUri }}
---
apiVersion: v1
kind: EndpointSlice
metadata:
  name: {{ include "xnat.postgresql.fullname" . }}
  labels:
{{- include "xnat.labels" . | nindent 4 }}
    kubernetes.io/service-name: {{ include "xnat.postgresql.fullname" . }}
addressType: IPv4
endpoints:
  - addresses:
      - "{{ .Values.cnpg.external.postgresqlUri }}"
{{- end }}
